#include "oal/oal_server.h"
#include "core/application_controller.h"
#include <QHttpServerRequest>
#include <QHttpServerResponse>
#include <QJsonDocument>
#include <opencv2/imgcodecs.hpp>

namespace oas { namespace {
using Status=QHttpServerResponse::StatusCode;
QHttpServerResponse response(const QJsonObject&o,Status s=Status::Ok){return QHttpServerResponse(o,s);}QHttpServerResponse ok(const QJsonValue&d=QJsonObject{}){return response({{"ok",true},{"error",QJsonValue::Null},{"data",d}});}QHttpServerResponse fail(QString code,QString msg,Status s=Status::BadRequest){return response({{"ok",false},{"error",QJsonObject{{"code",code},{"message",msg},{"details",QJsonValue::Null}}},{"data",QJsonValue::Null}},s);}QJsonObject body(const QHttpServerRequest&r,bool*valid=nullptr){QJsonParseError e;auto d=QJsonDocument::fromJson(r.body(),&e);bool v=e.error==QJsonParseError::NoError&&d.isObject();if(valid)*valid=v;return v?d.object():QJsonObject{};}AutofocusMode mode(const QString&s){if(s=="planet")return AutofocusMode::Planet;if(s=="bahtinov")return AutofocusMode::Bahtinov;return AutofocusMode::Stars;}GuideDirection dir(const QString&s){if(s=="south")return GuideDirection::South;if(s=="east")return GuideDirection::East;if(s=="west")return GuideDirection::West;return GuideDirection::North;}QJsonObject sessionJsonLocal(const SessionStatus&s){return{{"id",s.id},{"name",s.name},{"active",s.active},{"targetIndex",s.targetIndex},{"targetCount",s.targetCount},{"completedFrames",s.completedFrames},{"state",s.state}};}
}
OalServer::OalServer(ApplicationController*c,QObject*p):QObject(p),controller_(c),http_(this),tcp_(this){registerRoutes();}
bool OalServer::start(quint16 p,QString*e){if(tcp_.isListening())tcp_.close();if(!tcp_.listen(QHostAddress::Any,p)){if(e)*e=tcp_.errorString();return false;}if(!bound_){if(!http_.bind(&tcp_)){if(e)*e="QHttpServer bind failed";tcp_.close();return false;}bound_=true;}return true;}
void OalServer::stop(){tcp_.close();}
void OalServer::registerRoutes(){
    http_.route("/api/v1/devices",QHttpServerRequest::Method::Get,[this](){return ok(QJsonObject{{"devices",controller_->devicesJson()}});});
    http_.route("/api/v1/state",QHttpServerRequest::Method::Get,[this](){return ok(controller_->stateJson());});
    http_.route("/api/v1/mounts/<arg>/status",QHttpServerRequest::Method::Get,[this](QString){MountStatus s;QString e;if(!controller_->mountStatus(s,&e))return fail("MOUNT_STATUS_FAILED",e,Status::ServiceUnavailable);return ok(QJsonObject{{"raDeg",s.coordinate.raDeg},{"decDeg",s.coordinate.decDeg},{"tracking",s.tracking},{"slewing",s.slewing},{"parked",s.parked},{"pierSide",s.pierSide}});});
    http_.route("/api/v1/mounts/<arg>/slew",QHttpServerRequest::Method::Post,[this](QString,const QHttpServerRequest&r){bool v;auto b=body(r,&v);if(!v)return fail("INVALID_JSON","JSON object required");QString e;if(!controller_->slewMount({b.value("raDeg").toDouble(),b.value("decDeg").toDouble()},&e))return fail("MOUNT_SLEW_FAILED",e,Status::ServiceUnavailable);return ok();});
    http_.route("/api/v1/mounts/<arg>/sync",QHttpServerRequest::Method::Post,[this](QString,const QHttpServerRequest&r){auto b=body(r);QString e;if(!controller_->syncMount({b.value("raDeg").toDouble(),b.value("decDeg").toDouble()},&e))return fail("MOUNT_SYNC_FAILED",e,Status::ServiceUnavailable);return ok();});
    http_.route("/api/v1/mounts/<arg>/tracking",QHttpServerRequest::Method::Post,[this](QString,const QHttpServerRequest&r){auto b=body(r);QString e;if(!controller_->setMountTracking(b.value("enabled").toBool(),&e))return fail("TRACKING_FAILED",e,Status::ServiceUnavailable);return ok();});
    http_.route("/api/v1/mounts/<arg>/park",QHttpServerRequest::Method::Post,[this](QString,const QHttpServerRequest&r){auto b=body(r);QString e;if(!controller_->parkMount(b.value("parked").toBool(true),&e))return fail("PARK_FAILED",e,Status::ServiceUnavailable);return ok();});
    http_.route("/api/v1/mounts/<arg>/pulse-guide",QHttpServerRequest::Method::Post,[this](QString,const QHttpServerRequest&r){auto b=body(r);QString e;if(!controller_->pulseGuide(dir(b.value("direction").toString()),b.value("durationMs").toInt(),&e))return fail("PULSE_GUIDE_FAILED",e,Status::ServiceUnavailable);return ok();});
    http_.route("/api/v1/focusers/<arg>/status",QHttpServerRequest::Method::Get,[this](QString){FocuserStatus s;QString e;if(!controller_->focuserStatus(s,&e))return fail("FOCUSER_STATUS_FAILED",e,Status::ServiceUnavailable);QJsonObject d{{"position",s.position},{"moving",s.moving}};if(s.temperatureC)d["temperatureC"]=*s.temperatureC;return ok(d);});
    http_.route("/api/v1/focusers/<arg>/move",QHttpServerRequest::Method::Post,[this](QString,const QHttpServerRequest&r){auto b=body(r);QString e;if(!controller_->moveFocuser(b.value("position").toInt(),&e))return fail("FOCUSER_MOVE_FAILED",e,Status::ServiceUnavailable);return ok();});
    http_.route("/api/v1/focusers/<arg>/move-relative",QHttpServerRequest::Method::Post,[this](QString,const QHttpServerRequest&r){FocuserStatus s;QString e;if(!controller_->focuserStatus(s,&e))return fail("FOCUSER_STATUS_FAILED",e,Status::ServiceUnavailable);auto b=body(r);if(!controller_->moveFocuser(s.position+b.value("delta").toInt(),&e))return fail("FOCUSER_MOVE_FAILED",e,Status::ServiceUnavailable);return ok();});
    http_.route("/api/v1/focusers/<arg>/halt",QHttpServerRequest::Method::Post,[this](QString){QString e;if(!controller_->haltFocuser(&e))return fail("FOCUSER_HALT_FAILED",e,Status::ServiceUnavailable);return ok();});
    http_.route("/api/v1/cameras/<arg>/status",QHttpServerRequest::Method::Get,[this](QString){auto d=controller_->cameraStatusJson();return d.value("connected").toBool()?ok(d):fail("CAMERA_DISCONNECTED","No camera connected",Status::ServiceUnavailable);});
    http_.route("/api/v1/cameras/<arg>/capture",QHttpServerRequest::Method::Post,[this](QString,const QHttpServerRequest&r){auto b=body(r);ExposureRequest q;q.exposureSec=b.value("exposureSec").toDouble(1.0);q.binX=b.value("binX").toInt(1);q.binY=b.value("binY").toInt(1);q.gain=b.value("gain").toInt();q.offset=b.value("offset").toInt();CameraFrame f;QString e;if(!controller_->capture(q,&f,&e))return fail("CAPTURE_FAILED",e,Status::ServiceUnavailable);QJsonObject d{{"frameId",f.id},{"capturedUtc",f.capturedUtc.toString(Qt::ISODateWithMs)},{"width",f.image.cols},{"height",f.image.rows}};if(b.value("includeImage").toBool(true)){std::vector<uchar> png;cv::imencode(".png",f.image,png);QByteArray bytes(reinterpret_cast<const char*>(png.data()),qsizetype(png.size()));d["imagePngBase64"]=QString::fromLatin1(bytes.toBase64());}return ok(d);});
    http_.route("/api/v1/motion/estimate",QHttpServerRequest::Method::Post,[this](){auto m=controller_->estimateLastMotion();QJsonObject d{{"valid",m.valid},{"dxPx",m.dxPx},{"dyPx",m.dyPx},{"rotationDeg",m.rotationDeg},{"scale",m.scale},{"inliers",m.inliers}};return m.valid?ok(d):fail("MOTION_FAILED","Two matchable frames are required",Status::BadRequest);});
    http_.route("/api/v1/observer/system-location",QHttpServerRequest::Method::Post,[this](){controller_->requestSystemLocation();return QHttpServerResponse(QJsonObject{{"ok",true},{"error",QJsonValue::Null},{"data",QJsonObject{{"accepted",true}}}},Status::Accepted);});
    http_.route("/api/v1/solve",QHttpServerRequest::Method::Post,[this](const QHttpServerRequest&r){auto b=body(r);SolveHint h;if(b.contains("hintRaDeg"))h.raDeg=b.value("hintRaDeg").toDouble();if(b.contains("hintDecDeg"))h.decDeg=b.value("hintDecDeg").toDouble();if(b.contains("hintFovDeg"))h.fovDeg=b.value("hintFovDeg").toDouble();h.searchRadiusDeg=b.value("searchRadiusDeg").toDouble(20.0);auto s=controller_->solveLast(h);return s.success?ok(solveToJson(s)):fail("SOLVE_FAILED",s.message,Status::BadRequest);});
    http_.route("/api/v1/autofocus/<arg>/run",QHttpServerRequest::Method::Post,[this](QString,const QHttpServerRequest&r){auto b=body(r);AutofocusRequest q;q.mode=mode(b.value("mode").toString("stars"));q.rangeSteps=b.value("rangeSteps").toInt(1600);q.coarseStep=b.value("coarseStep").toInt(200);q.fineStep=b.value("fineStep").toInt(40);q.framesPerPosition=b.value("framesPerPosition").toInt(3);q.settleMs=b.value("settleMs").toInt(400);q.autoPlanetRoi=b.value("autoPlanetRoi").toBool(true);auto x=controller_->autofocus(q);return x.success?ok(autofocusToJson(x)):fail("AUTOFOCUS_FAILED",x.message,Status::BadRequest);});
    http_.route("/api/v1/guider/default/start",QHttpServerRequest::Method::Post,[this](){auto g=controller_->startGuiding();return ok(QJsonObject{{"active",g.active},{"raErrorArcsec",g.raErrorArcsec},{"decErrorArcsec",g.decErrorArcsec},{"rmsArcsec",g.rmsArcsec}});});
    http_.route("/api/v1/guider/default/stop",QHttpServerRequest::Method::Post,[this](){auto g=controller_->stopGuiding();return ok(QJsonObject{{"active",g.active}});});
    http_.route("/api/v1/guider/default/status",QHttpServerRequest::Method::Get,[this](){auto g=controller_->guidingStatus();return ok(QJsonObject{{"active",g.active},{"raErrorArcsec",g.raErrorArcsec},{"decErrorArcsec",g.decErrorArcsec},{"rmsArcsec",g.rmsArcsec}});});
    http_.route("/api/v1/polar-align/sample",QHttpServerRequest::Method::Post,[this](){QString e;if(!controller_->addPolarSample(&e))return fail("POLAR_SAMPLE_FAILED",e,Status::BadRequest);return ok();});
    http_.route("/api/v1/polar-align/ra-offset",QHttpServerRequest::Method::Post,[this](const QHttpServerRequest&r){auto b=body(r);QString e;if(!controller_->slewPolarRaOffset(b.value("deltaDeg").toDouble(),&e))return fail("POLAR_SLEW_FAILED",e,Status::ServiceUnavailable);return ok();});
    http_.route("/api/v1/polar-align/estimate",QHttpServerRequest::Method::Get,[this](){auto p=controller_->estimatePolarAlignment();QJsonObject d{{"success",p.success},{"axisRaDeg",p.axisRaDeg},{"axisDecDeg",p.axisDecDeg},{"totalErrorArcmin",p.totalErrorArcmin},{"altitudeAdjustmentArcmin",p.altitudeAdjustmentArcmin},{"azimuthAdjustmentArcmin",p.azimuthAdjustmentArcmin},{"message",p.message}};return p.success?ok(d):fail("POLAR_ESTIMATE_FAILED",p.message,Status::BadRequest);});
    http_.route("/api/v1/sessions",QHttpServerRequest::Method::Post,[this](const QHttpServerRequest&r){auto b=body(r);std::vector<SessionTarget> ts;for(auto v:b.value("targets").toArray()){auto x=v.toObject();ts.push_back({x.value("name").toString(),{x.value("raDeg").toDouble(),x.value("decDeg").toDouble()},x.value("exposureSec").toDouble(30),x.value("repeats").toInt(1),x.value("filter").toString()});}controller_->scheduler().setPlan(b.value("name").toString("OAL session"),std::move(ts));if(!controller_->scheduler().start())return fail("SESSION_START_FAILED","No targets supplied",Status::BadRequest);return ok(sessionJsonLocal(controller_->scheduler().status()));});
    http_.route("/api/v1/sessions/current",QHttpServerRequest::Method::Get,[this](){return ok(sessionJsonLocal(controller_->scheduler().status()));});
}
} // namespace oas
