#include "gui/main_window.h"
#include <QCheckBox>
#include <QComboBox>
#include <QDoubleSpinBox>
#include <QFormLayout>
#include <QGraphicsEllipseItem>
#include <QGraphicsScene>
#include <QGraphicsView>
#include <QGroupBox>
#include <QHBoxLayout>
#include <QLabel>
#include <QLineEdit>
#include <QListWidget>
#include <QMessageBox>
#include <QPainter>
#include <QPushButton>
#include <QSpinBox>
#include <QSplitter>
#include <QTabWidget>
#include <QTextEdit>
#include <QVBoxLayout>
#include <QTime>
#include <algorithm>
#include <cmath>

namespace oas {
static QDoubleSpinBox *dspin(double lo,double hi,double value,int decimals=4){auto*w=new QDoubleSpinBox;w->setRange(lo,hi);w->setDecimals(decimals);w->setValue(value);return w;}
static QSpinBox *ispin(int lo,int hi,int value){auto*w=new QSpinBox;w->setRange(lo,hi);w->setValue(value);return w;}
MainWindow::MainWindow(ApplicationController*c,QWidget*p):QMainWindow(p),c_(c){setWindowTitle("OpenAstroSuite / OpenAstroLink");resize(1500,900);auto*central=new QWidget;auto*root=new QHBoxLayout(central);auto*split=new QSplitter(Qt::Horizontal);root->addWidget(split);setCentralWidget(central);
    auto*left=new QWidget;auto*ll=new QVBoxLayout(left);auto*images=new QSplitter(Qt::Horizontal);rawImage_=new QLabel("No camera frame");astroImage_=new QLabel("No astrometry overlay");for(auto*l:{rawImage_,astroImage_}){l->setAlignment(Qt::AlignCenter);l->setMinimumSize(420,300);l->setStyleSheet("background:#111;color:#bbb;border:1px solid #444");}images->addWidget(rawImage_);images->addWidget(astroImage_);ll->addWidget(images,3);starScene_=new QGraphicsScene(this);auto*map=new QGraphicsView(starScene_);map->setMinimumHeight(220);map->setStyleSheet("background:#050510");ll->addWidget(map,1);log_=new QTextEdit;log_->setReadOnly(true);log_->setMaximumHeight(170);ll->addWidget(log_);split->addWidget(left);
    auto*tabs=new QTabWidget;tabs->addTab(buildDevicesTab(),"Devices");tabs->addTab(buildCaptureTab(),"Capture & Solve");tabs->addTab(buildMountTab(),"Mount & Guide");tabs->addTab(buildFocusTab(),"Focus");tabs->addTab(buildPolarTab(),"Polar Align");tabs->addTab(buildSchedulerTab(),"Scheduler");tabs->addTab(buildServerTab(),"OAL Server");tabs->addTab(buildProfileTab(),"Profile");split->addWidget(tabs);split->setStretchFactor(0,4);split->setStretchFactor(1,2);
    connect(c_,&ApplicationController::logMessage,this,&MainWindow::appendLog);connect(c_,&ApplicationController::frameCaptured,this,[this](const QImage&i,const QString&id){lastImage_=i;rawImage_->setPixmap(QPixmap::fromImage(i).scaled(rawImage_->size(),Qt::KeepAspectRatio,Qt::SmoothTransformation));appendLog("Frame: "+id);});connect(c_,&ApplicationController::solveCompleted,this,[this](const QJsonObject&o){appendLog(QString("Solve: %1 RA=%2 DEC=%3 matches=%4").arg(o.value("success").toBool()?"OK":"FAIL").arg(o.value("raDeg").toDouble()).arg(o.value("decDeg").toDouble()).arg(o.value("matchedStars").toInt()));updateAstrometryOverlay();updateStarMap();});connect(c_,&ApplicationController::autofocusProgress,this,[this](const QJsonObject&o){appendLog(QString("AF pos=%1 score=%2").arg(o.value("position").toInt()).arg(o.value("score").toDouble()));});connect(c_,&ApplicationController::autofocusCompleted,this,[this](const QJsonObject&o){appendLog(QString("AF %1 best=%2 score=%3").arg(o.value("success").toBool()?"OK":"FAIL").arg(o.value("bestPosition").toInt()).arg(o.value("bestScore").toDouble()));});connect(c_,&ApplicationController::polarSampleCountChanged,this,[this](int n){polarSamples_->setText(QString("Samples: %1").arg(n));});connect(c_,&ApplicationController::sessionChanged,this,[this](const QJsonObject&o){appendLog(QString("Session %1: %2").arg(o.value("name").toString(),o.value("state").toString()));});connect(c_,&ApplicationController::motionEstimated,this,[this](const QJsonObject&o){appendLog(QString("Motion valid=%1 dx=%2 px dy=%3 px rot=%4° inliers=%5").arg(o.value("valid").toBool()).arg(o.value("dxPx").toDouble()).arg(o.value("dyPx").toDouble()).arg(o.value("rotationDeg").toDouble()).arg(o.value("inliers").toInt()));});connect(c_,&ApplicationController::profileChanged,this,[this](){auto p=c_->profile();if(lat_){lat_->setValue(p.observer.latitudeDeg);lon_->setValue(p.observer.longitudeDeg);elevation_->setValue(p.observer.elevationM);}});}
QWidget *MainWindow::buildDevicesTab(){auto*w=new QWidget;auto*l=new QVBoxLayout(w);auto make=[&](const QString&name,QComboBox*&combo,QLineEdit*&endpoint,const QStringList&items,auto callback){auto*g=new QGroupBox(name);auto*f=new QFormLayout(g);combo=new QComboBox;combo->addItems(items);endpoint=new QLineEdit;auto*b=new QPushButton("Connect");f->addRow("Backend",combo);f->addRow("Endpoint / index",endpoint);f->addRow(b);connect(b,&QPushButton::clicked,this,[this,combo,endpoint,callback](){QString e;if(!(c_->*callback)(combo->currentText(),endpoint->text(),&e))showError(e);});l->addWidget(g);};make("Camera",cameraBackend_,cameraEndpoint_,c_->cameraBackends(),&ApplicationController::connectCamera);cameraEndpoint_->setText("0");make("Mount",mountBackend_,mountEndpoint_,c_->mountBackends(),&ApplicationController::connectMount);mountEndpoint_->setPlaceholderText("COM3, /dev/ttyUSB0 or URL");make("Focuser",focuserBackend_,focuserEndpoint_,c_->focuserBackends(),&ApplicationController::connectFocuser);focuserEndpoint_->setPlaceholderText("Gemini: alpaca:<URL> or indi:host:7624/device; Alpaca/OAL URL");auto*d=new QPushButton("Disconnect all");connect(d,&QPushButton::clicked,c_,&ApplicationController::disconnectAll);l->addWidget(d);l->addStretch();return w;}
QWidget *MainWindow::buildCaptureTab(){auto*w=new QWidget;auto*l=new QVBoxLayout(w);auto*f=new QFormLayout;exposure_=dspin(0.0001,3600,1,4);gain_=ispin(0,10000,0);solverBackend_=new QComboBox;solverBackend_->addItems(c_->solverBackends());catalogPath_=new QLineEdit("config/stars_example.csv");modelPath_=new QLineEdit;hintRa_=dspin(0,360,83.8221,6);hintDec_=dspin(-90,90,-5.3911,6);hintRadius_=dspin(0.1,180,20,2);f->addRow("Exposure, s",exposure_);f->addRow("Gain",gain_);f->addRow("Solver",solverBackend_);f->addRow("Catalog CSV",catalogPath_);f->addRow("Neural model",modelPath_);f->addRow("Hint RA, deg",hintRa_);f->addRow("Hint DEC, deg",hintDec_);f->addRow("Search radius, deg",hintRadius_);l->addLayout(f);auto*loadCatalog=new QPushButton("Load catalog");auto*loadModel=new QPushButton("Load neural model");connect(loadCatalog,&QPushButton::clicked,this,[this](){QString e;if(!c_->loadCatalog(catalogPath_->text(),&e))showError(e);});connect(loadModel,&QPushButton::clicked,this,[this](){QString e;if(!c_->loadNeuralModel(modelPath_->text(),&e))showError(e);});connect(solverBackend_,&QComboBox::currentTextChanged,this,[this](const QString&x){QString e;if(!c_->selectSolver(x,&e))showError(e);});auto*capture=new QPushButton("Capture");auto*solve=new QPushButton("Solve last frame");auto*both=new QPushButton("Capture + solve");auto*motion=new QPushButton("Estimate motion between last two frames");connect(capture,&QPushButton::clicked,this,[this](){ExposureRequest r;r.exposureSec=exposure_->value();r.gain=gain_->value();QString e;if(!c_->capture(r,nullptr,&e))showError(e);});auto doSolve=[this](){SolveHint h;h.raDeg=hintRa_->value();h.decDeg=hintDec_->value();h.searchRadiusDeg=hintRadius_->value();c_->solveLast(h);};connect(solve,&QPushButton::clicked,this,doSolve);connect(both,&QPushButton::clicked,this,[this,doSolve](){ExposureRequest r;r.exposureSec=exposure_->value();r.gain=gain_->value();QString e;if(c_->capture(r,nullptr,&e))doSolve();else showError(e);});connect(motion,&QPushButton::clicked,this,[this](){c_->estimateLastMotion();});l->addWidget(loadCatalog);l->addWidget(loadModel);l->addWidget(capture);l->addWidget(solve);l->addWidget(both);l->addWidget(motion);l->addStretch();return w;}
QWidget *MainWindow::buildMountTab(){auto*w=new QWidget;auto*l=new QVBoxLayout(w);auto*f=new QFormLayout;mountRa_=dspin(0,360,83.8221,6);mountDec_=dspin(-90,90,-5.3911,6);f->addRow("RA deg",mountRa_);f->addRow("DEC deg",mountDec_);l->addLayout(f);auto*slew=new QPushButton("Slew");auto*sync=new QPushButton("Sync");connect(slew,&QPushButton::clicked,this,[this](){QString e;if(!c_->slewMount({mountRa_->value(),mountDec_->value()},&e))showError(e);});connect(sync,&QPushButton::clicked,this,[this](){QString e;if(!c_->syncMount({mountRa_->value(),mountDec_->value()},&e))showError(e);});l->addWidget(slew);l->addWidget(sync);auto*track=new QCheckBox("Tracking");connect(track,&QCheckBox::toggled,this,[this](bool v){QString e;if(!c_->setMountTracking(v,&e))appendLog(e);});auto*park=new QCheckBox("Parked");connect(park,&QCheckBox::toggled,this,[this](bool v){QString e;if(!c_->parkMount(v,&e))appendLog(e);});l->addWidget(track);l->addWidget(park);auto*gs=new QPushButton("Set guide target from last solve");auto*gu=new QPushButton("Guide using last solve");auto*gx=new QPushButton("Stop guiding");connect(gs,&QPushButton::clicked,this,[this](){c_->startGuiding();});connect(gu,&QPushButton::clicked,this,[this](){c_->guideUsingLastSolve();});connect(gx,&QPushButton::clicked,this,[this](){c_->stopGuiding();});l->addWidget(gs);l->addWidget(gu);l->addWidget(gx);l->addStretch();return w;}
QWidget *MainWindow::buildFocusTab(){auto*w=new QWidget;auto*l=new QVBoxLayout(w);auto*f=new QFormLayout;focusPosition_=ispin(0,200000,20000);focusMode_=new QComboBox;focusMode_->addItems({"stars","planet","bahtinov"});focusRange_=ispin(100,50000,1600);coarseStep_=ispin(1,10000,200);fineStep_=ispin(1,5000,40);focusFrames_=ispin(1,30,3);f->addRow("Absolute position",focusPosition_);f->addRow("AF mode",focusMode_);f->addRow("Range",focusRange_);f->addRow("Coarse step",coarseStep_);f->addRow("Fine step",fineStep_);f->addRow("Frames / point",focusFrames_);l->addLayout(f);auto*move=new QPushButton("Move focuser");connect(move,&QPushButton::clicked,this,[this](){QString e;if(!c_->moveFocuser(focusPosition_->value(),&e))showError(e);});auto*af=new QPushButton("Run autofocus");connect(af,&QPushButton::clicked,this,[this](){AutofocusRequest r;r.mode=focusMode_->currentText()=="planet"?AutofocusMode::Planet:focusMode_->currentText()=="bahtinov"?AutofocusMode::Bahtinov:AutofocusMode::Stars;r.rangeSteps=focusRange_->value();r.coarseStep=coarseStep_->value();r.fineStep=fineStep_->value();r.framesPerPosition=focusFrames_->value();c_->autofocus(r);});l->addWidget(move);l->addWidget(af);l->addStretch();return w;}
QWidget *MainWindow::buildPolarTab(){auto*w=new QWidget;auto*l=new QVBoxLayout(w);polarStep_=dspin(-60,60,15,2);polarSamples_=new QLabel("Samples: 0");polarResult_=new QLabel("No estimate");polarResult_->setWordWrap(true);auto*clear=new QPushButton("Clear samples");auto*add=new QPushButton("Add last solved field");auto*slew=new QPushButton("Slew RA by step");auto*estimate=new QPushButton("Estimate RA axis");connect(clear,&QPushButton::clicked,c_,&ApplicationController::clearPolarSamples);connect(add,&QPushButton::clicked,this,[this](){QString e;if(!c_->addPolarSample(&e))showError(e);});connect(slew,&QPushButton::clicked,this,[this](){QString e;if(!c_->slewPolarRaOffset(polarStep_->value(),&e))showError(e);});connect(estimate,&QPushButton::clicked,this,[this](){auto r=c_->estimatePolarAlignment();polarResult_->setText(QString("%1\nAxis RA %2°, DEC %3°\nTotal %4′\nAdjust altitude %5′, azimuth %6′").arg(r.message).arg(r.axisRaDeg).arg(r.axisDecDeg).arg(r.totalErrorArcmin).arg(r.altitudeAdjustmentArcmin).arg(r.azimuthAdjustmentArcmin));});l->addWidget(polarSamples_);l->addWidget(new QLabel("RA step, deg"));l->addWidget(polarStep_);l->addWidget(clear);l->addWidget(add);l->addWidget(slew);l->addWidget(estimate);l->addWidget(polarResult_);l->addStretch();return w;}
QWidget *MainWindow::buildSchedulerTab(){auto*w=new QWidget;auto*l=new QVBoxLayout(w);auto*f=new QFormLayout;targetName_=new QLineEdit("M42");targetRa_=dspin(0,360,83.8221,6);targetDec_=dspin(-90,90,-5.3911,6);targetExposure_=dspin(0.001,3600,30,3);targetRepeats_=ispin(1,10000,10);f->addRow("Name",targetName_);f->addRow("RA",targetRa_);f->addRow("DEC",targetDec_);f->addRow("Exposure",targetExposure_);f->addRow("Repeats",targetRepeats_);l->addLayout(f);targetList_=new QListWidget;l->addWidget(targetList_);auto*add=new QPushButton("Add target");auto*start=new QPushButton("Start plan");auto*stop=new QPushButton("Stop");connect(add,&QPushButton::clicked,this,[this](){SessionTarget t{targetName_->text(),{targetRa_->value(),targetDec_->value()},targetExposure_->value(),targetRepeats_->value(),{}};targets_.push_back(t);targetList_->addItem(QString("%1  RA %2 DEC %3  %4s × %5").arg(t.name).arg(t.coordinate.raDeg).arg(t.coordinate.decDeg).arg(t.exposureSec).arg(t.repeats));});connect(start,&QPushButton::clicked,this,[this](){c_->scheduler().setPlan("GUI observing plan",targets_);if(!c_->scheduler().start())showError("Add at least one target");});Scheduler *sched=&c_->scheduler();connect(stop,&QPushButton::clicked,sched,&Scheduler::stop);l->addWidget(add);l->addWidget(start);l->addWidget(stop);return w;}
QWidget *MainWindow::buildServerTab(){auto*w=new QWidget;auto*l=new QVBoxLayout(w);serverEnabled_=new QCheckBox("Enable OAL HTTP server");serverPort_=ispin(1,65535,8080);wsEnabled_=new QCheckBox("Enable event WebSocket");wsPort_=ispin(1,65535,8090);auto*f=new QFormLayout;f->addRow(serverEnabled_);f->addRow("HTTP port",serverPort_);f->addRow(wsEnabled_);f->addRow("WebSocket port",wsPort_);l->addLayout(f);auto*apply=new QPushButton("Apply server settings");connect(apply,&QPushButton::clicked,this,[this](){if(!serverEnabled_->isChecked()){c_->stopOalServer();appendLog("OAL server stopped");return;}QString e;if(!c_->startOalServer(serverPort_->value(),wsEnabled_->isChecked(),wsPort_->value(),&e))showError(e);});l->addWidget(apply);l->addWidget(new QLabel("HTTP API: /api/v1\nEvents: ws://host:port"));l->addStretch();return w;}
QWidget *MainWindow::buildProfileTab(){auto*w=new QWidget;auto*l=new QVBoxLayout(w);auto p=c_->profile();auto*f=new QFormLayout;focal_=dspin(1,100000,p.focalLengthMm,3);pixel_=dspin(0.1,100,p.pixelSizeUm,3);sensorW_=ispin(1,100000,p.sensorWidthPx);sensorH_=ispin(1,100000,p.sensorHeightPx);lat_=dspin(-90,90,p.observer.latitudeDeg,6);lon_=dspin(-180,180,p.observer.longitudeDeg,6);elevation_=dspin(-500,10000,p.observer.elevationM,1);f->addRow("Focal length mm",focal_);f->addRow("Pixel μm",pixel_);f->addRow("Sensor width",sensorW_);f->addRow("Sensor height",sensorH_);f->addRow("Latitude",lat_);f->addRow("Longitude",lon_);f->addRow("Elevation m",elevation_);l->addLayout(f);auto*save=new QPushButton("Save profile");connect(save,&QPushButton::clicked,this,[this](){auto p=c_->profile();p.focalLengthMm=focal_->value();p.pixelSizeUm=pixel_->value();p.sensorWidthPx=sensorW_->value();p.sensorHeightPx=sensorH_->value();p.observer={lat_->value(),lon_->value(),elevation_->value()};c_->setProfile(p);appendLog(QString("Profile saved; scale %1 arcsec/px").arg(p.arcsecPerPixel()));});auto*systemLocation=new QPushButton("Use system location");connect(systemLocation,&QPushButton::clicked,c_,&ApplicationController::requestSystemLocation);l->addWidget(save);l->addWidget(systemLocation);l->addStretch();return w;}
void MainWindow::appendLog(const QString&s){log_->append(QTime::currentTime().toString("HH:mm:ss ")+s);}void MainWindow::showError(const QString&s){appendLog("ERROR: "+s);QMessageBox::warning(this,"OpenAstroSuite",s);}void MainWindow::updateAstrometryOverlay(){if(lastImage_.isNull())return;QImage o=lastImage_.copy();QPainter p(&o);p.setPen(QPen(Qt::green,2));for(const auto&s:c_->lastSolve().imageStars)p.drawEllipse(QPointF(s.positionPx.x,s.positionPx.y),6,6);p.setPen(Qt::yellow);p.drawText(12,24,QString("RA %1  DEC %2  PA %3  matches %4").arg(c_->lastSolve().raDeg,0,'f',5).arg(c_->lastSolve().decDeg,0,'f',5).arg(c_->lastSolve().rotationDeg,0,'f',2).arg(c_->lastSolve().matchedStars));astroImage_->setPixmap(QPixmap::fromImage(o).scaled(astroImage_->size(),Qt::KeepAspectRatio,Qt::SmoothTransformation));}void MainWindow::updateStarMap(){starScene_->clear();starScene_->setSceneRect(0,0,600,200);starScene_->addRect(starScene_->sceneRect(),QPen(Qt::darkBlue),QBrush(QColor(3,3,16)));if(c_->lastFrame().image.empty())return;double sx=600.0/c_->lastFrame().image.cols,sy=200.0/c_->lastFrame().image.rows;for(const auto&s:c_->lastSolve().imageStars){double r=std::clamp(2.0+std::log1p(s.flux),2.0,8.0);starScene_->addEllipse(s.positionPx.x*sx-r,s.positionPx.y*sy-r,2*r,2*r,QPen(Qt::white),QBrush(Qt::white));}auto*t=starScene_->addText(QString("Solved center RA %1° DEC %2°").arg(c_->lastSolve().raDeg,0,'f',4).arg(c_->lastSolve().decDeg,0,'f',4));t->setDefaultTextColor(Qt::cyan);t->setPos(8,8);}
} // namespace oas
