#include "algorithms/pattern_plate_solver.h"
#include <opencv2/calib3d.hpp>
#include <opencv2/imgproc.hpp>
#include <algorithm>
#include <array>
#include <cmath>

namespace oas {
namespace {
constexpr double PI=3.14159265358979323846,D2R=PI/180.0,R2D=180.0/PI;
struct P{double x,y;};
P project(double ra0,double de0,double ra,double de){ra0*=D2R;de0*=D2R;ra*=D2R;de*=D2R;double dra=ra-ra0,c=std::sin(de0)*std::sin(de)+std::cos(de0)*std::cos(de)*std::cos(dra);return {std::cos(de)*std::sin(dra)/c,(std::cos(de0)*std::sin(de)-std::sin(de0)*std::cos(de)*std::cos(dra))/c};}
std::pair<double,double> unproject(double ra0,double de0,double x,double y){ra0*=D2R;de0*=D2R;double rho=std::hypot(x,y);if(rho<1e-15)return{ra0*R2D,de0*R2D};double c=std::atan(rho),sc=std::sin(c),cc=std::cos(c);double de=std::asin(cc*std::sin(de0)+y*sc*std::cos(de0)/rho);double ra=ra0+std::atan2(x*sc,rho*std::cos(de0)*cc-y*std::sin(de0)*sc);double rd=std::fmod(ra*R2D+360.0,360.0);return{rd,de*R2D};}
std::array<double,2> desc(P a,P b,P c){double d[3]={std::hypot(a.x-b.x,a.y-b.y),std::hypot(a.x-c.x,a.y-c.y),std::hypot(b.x-c.x,b.y-c.y)};std::sort(d,d+3);return{d[0]/d[2],d[1]/d[2]};}
}
SolveResult PatternPlateSolver::solve(const CameraFrame &frame,const TelescopeProfile &profile,const SolveHint &hint){SolveResult best;best.catalog="CSV";if(!catalog_||catalog_->stars().size()<6){best.message="Catalog is not loaded";return best;}auto img=detector_.detect(frame.image);best.imageStars=img;if(img.size()<4){best.message="Fewer than four image stars";return best;}if(img.size()>12)img.resize(12);const double scaleRad=profile.arcsecPerPixel()/206264.806;std::vector<CatalogStar> cat;if(hint.raDeg&&hint.decDeg)cat=catalog_->around(*hint.raDeg,*hint.decDeg,std::max(3.0,hint.searchRadiusDeg),12.0,70);else{cat=catalog_->stars();if(cat.size()>70)cat.resize(70);}if(cat.size()<4){best.message="Too few catalog stars in search region";return best;}
    struct CT{int a,b,c;std::array<double,2>d;};std::vector<CT> cts;for(int a=0;a<int(cat.size())-2;++a)for(int b=a+1;b<int(cat.size())-1;++b)for(int c=b+1;c<int(cat.size());++c){auto pb=project(cat[a].raDeg,cat[a].decDeg,cat[b].raDeg,cat[b].decDeg);auto pc=project(cat[a].raDeg,cat[a].decDeg,cat[c].raDeg,cat[c].decDeg);cts.push_back({a,b,c,desc({0,0},pb,pc)});}const double tol=0.012,matchRad=30.0/206264.806;cv::Point2d imageCenter(frame.image.cols*0.5,frame.image.rows*0.5);
    for(int ia=0;ia<int(img.size())-2;++ia)for(int ib=ia+1;ib<int(img.size())-1;++ib)for(int ic=ib+1;ic<int(img.size());++ic){P ip[3]={{(img[ia].positionPx.x-img[ia].positionPx.x)*scaleRad,-(img[ia].positionPx.y-img[ia].positionPx.y)*scaleRad},{(img[ib].positionPx.x-img[ia].positionPx.x)*scaleRad,-(img[ib].positionPx.y-img[ia].positionPx.y)*scaleRad},{(img[ic].positionPx.x-img[ia].positionPx.x)*scaleRad,-(img[ic].positionPx.y-img[ia].positionPx.y)*scaleRad}};auto id=desc(ip[0],ip[1],ip[2]);for(const auto&ct:cts){if(std::abs(id[0]-ct.d[0])>tol||std::abs(id[1]-ct.d[1])>tol)continue;std::array<int,3> ids={ct.a,ct.b,ct.c};do{P cp[3]={{0,0},project(cat[ids[0]].raDeg,cat[ids[0]].decDeg,cat[ids[1]].raDeg,cat[ids[1]].decDeg),project(cat[ids[0]].raDeg,cat[ids[0]].decDeg,cat[ids[2]].raDeg,cat[ids[2]].decDeg)};cv::Point2f src[3]={{float(ip[0].x),float(ip[0].y)},{float(ip[1].x),float(ip[1].y)},{float(ip[2].x),float(ip[2].y)}};cv::Point2f dst[3]={{float(cp[0].x),float(cp[0].y)},{float(cp[1].x),float(cp[1].y)},{float(cp[2].x),float(cp[2].y)}};cv::Mat A=cv::getAffineTransform(src,dst);double det=A.at<double>(0,0)*A.at<double>(1,1)-A.at<double>(0,1)*A.at<double>(1,0);if(det<=0.2||det>=5.0)continue;std::vector<P> projCat;projCat.reserve(cat.size());for(auto&s:cat)projCat.push_back(project(cat[ids[0]].raDeg,cat[ids[0]].decDeg,s.raDeg,s.decDeg));int matches=0;double sum2=0;for(auto&s:img){double x=(s.positionPx.x-img[ia].positionPx.x)*scaleRad,y=-(s.positionPx.y-img[ia].positionPx.y)*scaleRad;double sx=A.at<double>(0,0)*x+A.at<double>(0,1)*y+A.at<double>(0,2),sy=A.at<double>(1,0)*x+A.at<double>(1,1)*y+A.at<double>(1,2);double md=1e9;for(auto&p:projCat)md=std::min(md,std::hypot(p.x-sx,p.y-sy));if(md<matchRad){++matches;sum2+=md*md;}}if(matches>best.matchedStars){double cx=(imageCenter.x-img[ia].positionPx.x)*scaleRad,cy=-(imageCenter.y-img[ia].positionPx.y)*scaleRad;double sx=A.at<double>(0,0)*cx+A.at<double>(0,1)*cy+A.at<double>(0,2),sy=A.at<double>(1,0)*cx+A.at<double>(1,1)*cy+A.at<double>(1,2);auto center=unproject(cat[ids[0]].raDeg,cat[ids[0]].decDeg,sx,sy);best.success=matches>=4;best.raDeg=center.first;best.decDeg=center.second;best.rotationDeg=std::atan2(A.at<double>(1,0),A.at<double>(0,0))*R2D;best.scaleArcsecPerPx=profile.arcsecPerPixel()*std::sqrt(std::abs(det));best.matchedStars=matches;best.rmsArcsec=matches?std::sqrt(sum2/matches)*206264.806:0;best.message=best.success?"Triangle match accepted":"Candidate below match threshold";}}while(std::next_permutation(ids.begin(),ids.end()));}}
    if(!best.success&&best.message.isEmpty())best.message="No catalog pattern matched";return best;}
}
