#ifdef OAS_HAVE_INDI
#include "backends/indi_devices.h"
#include <QRegularExpression>
#include <QElapsedTimer>

namespace oas {
IndiEndpoint IndiEndpoint::parse(const QString&s){IndiEndpoint e;QString x=s;int slash=x.indexOf('/');if(slash>=0){e.device=x.mid(slash+1);x=x.left(slash);}int colon=x.lastIndexOf(':');if(colon>=0){e.host=x.left(colon);e.port=x.mid(colon+1).toUShort();}else if(!x.isEmpty())e.host=x;return e;}
bool IndiXmlClient::connectServer(QString*e){socket_.connectToHost(ep_.host,ep_.port);if(!socket_.waitForConnected(5000)){if(e)*e=socket_.errorString();return false;}return setConnection(true,e);}void IndiXmlClient::close(){socket_.disconnectFromHost();}
bool IndiXmlClient::write(const QByteArray&b,QString*e){if(socket_.write(b)!=b.size()||!socket_.waitForBytesWritten(3000)){if(e)*e=socket_.errorString();return false;}return true;}
bool IndiXmlClient::setConnection(bool on,QString*e){return sendSwitch("CONNECTION",{{"CONNECT",on},{"DISCONNECT",!on}},e);}
QByteArray IndiXmlClient::queryProperty(const QString&name,int timeout,QString*e){QByteArray req=QString("<getProperties version='1.7' device='%1' name='%2'/>\n").arg(ep_.device,name).toUtf8();if(!write(req,e))return{};QByteArray all;QElapsedTimer t;t.start();while(t.elapsed()<timeout){if(socket_.waitForReadyRead(250))all+=socket_.readAll();if(all.contains(("name='"+name+"'").toUtf8())||all.contains(("name=\""+name+"\"").toUtf8()))break;}if(all.isEmpty()&&e)*e="INDI property timeout";return all;}
bool IndiXmlClient::sendNumber(const QString&n,const QList<QPair<QString,double>>&v,QString*e){QString x=QString("<newNumberVector device='%1' name='%2'>").arg(ep_.device,n);for(auto&p:v)x+=QString("<oneNumber name='%1'>%2</oneNumber>").arg(p.first).arg(p.second,0,'g',15);x+="</newNumberVector>\n";return write(x.toUtf8(),e);}
bool IndiXmlClient::sendSwitch(const QString&n,const QList<QPair<QString,bool>>&v,QString*e){QString x=QString("<newSwitchVector device='%1' name='%2'>").arg(ep_.device,n);for(auto&p:v)x+=QString("<oneSwitch name='%1'>%2</oneSwitch>").arg(p.first).arg(p.second?"On":"Off");x+="</newSwitchVector>\n";return write(x.toUtf8(),e);}
bool IndiXmlClient::number(const QByteArray&x,const QString&n,double&v){QRegularExpression re(QString("<(?:def|one)Number[^>]*name=['\"]%1['\"][^>]*>([^<]+)").arg(QRegularExpression::escape(n)));auto m=re.match(QString::fromUtf8(x));if(!m.hasMatch())return false;v=m.captured(1).toDouble();return true;}bool IndiXmlClient::switchValue(const QByteArray&x,const QString&n,bool&v){QRegularExpression re(QString("<(?:def|one)Switch[^>]*name=['\"]%1['\"][^>]*>(On|Off)").arg(QRegularExpression::escape(n)));auto m=re.match(QString::fromUtf8(x));if(!m.hasMatch())return false;v=m.captured(1)=="On";return true;}
bool IndiMount::connectDevice(QString*e){if(!client_.connectServer(e)){state_=ConnectionState::Error;return false;}state_=ConnectionState::Connected;return true;}void IndiMount::disconnectDevice(){client_.close();state_=ConnectionState::Disconnected;}bool IndiMount::status(MountStatus&s,QString*e){auto x=client_.queryProperty("EQUATORIAL_EOD_COORD",3000,e);double ra=0,de=0;if(!IndiXmlClient::number(x,"RA",ra)||!IndiXmlClient::number(x,"DEC",de))return false;s.connection=state_;s.coordinate={ra*15.0,de};auto t=client_.queryProperty("TELESCOPE_TRACK_STATE",1000,nullptr);IndiXmlClient::switchValue(t,"TRACK_ON",s.tracking);return true;}bool IndiMount::slewTo(const EquatorialCoord&t,QString*e){client_.sendSwitch("ON_COORD_SET",{{"SLEW",true},{"TRACK",false},{"SYNC",false}},e);return client_.sendNumber("EQUATORIAL_EOD_COORD",{{"RA",t.raDeg/15.0},{"DEC",t.decDeg}},e);}bool IndiMount::syncTo(const EquatorialCoord&t,QString*e){client_.sendSwitch("ON_COORD_SET",{{"SLEW",false},{"TRACK",false},{"SYNC",true}},e);return client_.sendNumber("EQUATORIAL_EOD_COORD",{{"RA",t.raDeg/15.0},{"DEC",t.decDeg}},e);}bool IndiMount::setTracking(bool v,QString*e){return client_.sendSwitch("TELESCOPE_TRACK_STATE",{{"TRACK_ON",v},{"TRACK_OFF",!v}},e);}bool IndiMount::park(bool v,QString*e){return client_.sendSwitch("TELESCOPE_PARK",{{"PARK",v},{"UNPARK",!v}},e);}bool IndiMount::pulseGuide(GuideDirection d,int ms,QString*e){if(d==GuideDirection::North||d==GuideDirection::South)return client_.sendNumber("TELESCOPE_TIMED_GUIDE_NS",{{"TIMED_GUIDE_N",d==GuideDirection::North?double(ms):0.0},{"TIMED_GUIDE_S",d==GuideDirection::South?double(ms):0.0}},e);return client_.sendNumber("TELESCOPE_TIMED_GUIDE_WE",{{"TIMED_GUIDE_W",d==GuideDirection::West?double(ms):0.0},{"TIMED_GUIDE_E",d==GuideDirection::East?double(ms):0.0}},e);}
bool IndiFocuser::connectDevice(QString*e){if(!client_.connectServer(e)){state_=ConnectionState::Error;return false;}state_=ConnectionState::Connected;return true;}void IndiFocuser::disconnectDevice(){client_.close();state_=ConnectionState::Disconnected;}bool IndiFocuser::status(FocuserStatus&s,QString*e){auto x=client_.queryProperty("ABS_FOCUS_POSITION",3000,e);double p=0;if(!IndiXmlClient::number(x,"FOCUS_ABSOLUTE_POSITION",p)&&!IndiXmlClient::number(x,"ABS_FOCUS_POSITION",p))return false;s.connection=state_;s.position=int(p);return true;}bool IndiFocuser::moveAbsolute(int p,QString*e){return client_.sendNumber("ABS_FOCUS_POSITION",{{"FOCUS_ABSOLUTE_POSITION",double(p)}},e);}bool IndiFocuser::moveRelative(int d,QString*e){FocuserStatus s;if(!status(s,e))return false;return moveAbsolute(s.position+d,e);}bool IndiFocuser::halt(QString*e){return client_.sendSwitch("FOCUS_ABORT_MOTION",{{"ABORT",true}},e);}
}
#endif
