#include "backends/oal_client_devices.h"
#include <QDateTime>
#include <QMutexLocker>
#include <QThread>
#include <opencv2/imgcodecs.hpp>
#include <algorithm>
namespace oas {
QUrl OalCameraClient::route(const QString&p)const{return appendPath(base_,p);}bool OalCameraClient::accepted(const HttpJsonClient::Reply&r,QString*e)const{if(!r.ok()||!r.json.value("ok").toBool()){if(e)*e=r.error.isEmpty()?r.json.value("error").toObject().value("message").toString("OAL request failed"):r.error;return false;}return true;}
bool OalCameraClient::connectDevice(QString*e){auto rep=http_.get(route("status"));if(!accepted(rep,e)){state_=ConnectionState::Error;return false;}auto d=rep.json.value("data").toObject();size_={d.value("width").toInt(),d.value("height").toInt()};state_=ConnectionState::Connected;return true;}
bool OalCameraClient::capture(const ExposureRequest&r,CameraFrame&f,QString*e){
    QJsonObject q{{"exposureSec",r.exposureSec},{"binX",r.binX},{"binY",r.binY},{"gain",r.gain},{"offset",r.offset}};
    auto rep=http_.postJson(route("capture"),q,10000);if(!accepted(rep,e))return false;auto op=rep.json.value("data").toObject();
    QString operationId=op.value("id").toString();
    // Backward compatibility with a pre-operation OAL camera endpoint.
    if(operationId.isEmpty()&&op.contains("frameId")){f.id=op.value("frameId").toString();f.capturedUtc=QDateTime::fromString(op.value("capturedUtc").toString(),Qt::ISODateWithMs);QByteArray png=QByteArray::fromBase64(op.value("imagePngBase64").toString().toLatin1());std::vector<uchar> bytes(png.begin(),png.end());f.image=cv::imdecode(bytes,cv::IMREAD_UNCHANGED);if(f.image.empty()){if(e)*e="OAL response did not contain a decodable image";return false;}f.exposureSec=r.exposureSec;f.gain=r.gain;f.binX=std::max(1,r.binX);f.binY=std::max(1,r.binY);f.source=id();size_={f.image.cols,f.image.rows};return true;}
    if(operationId.isEmpty()){if(e)*e="OAL node did not return an exposure operation id";return false;}
    {QMutexLocker lock(&exposureMutex_);activeExposureOperationId_=operationId;}
    auto nodeUrl=[this](const QString&suffix){QUrl u(base_);QString path=u.path();const int marker=path.indexOf("/cameras/");if(marker>=0)path=path.left(marker);while(path.endsWith('/'))path.chop(1);u.setPath(path+"/"+suffix);return u;};
    const int timeoutMs=std::max(120000,int(r.exposureSec*1000.0)+60000);int waited=0;QJsonObject done;
    while(waited<timeoutMs){auto rr=http_.get(nodeUrl("operations/"+operationId),5000);if(!accepted(rr,e)){QMutexLocker lock(&exposureMutex_);activeExposureOperationId_.clear();return false;}done=rr.json.value("data").toObject();const QString state=done.value("state").toString();if(state=="succeeded"||state=="failed"||state=="cancelled")break;QThread::msleep(100);waited+=100;}
    {QMutexLocker lock(&exposureMutex_);activeExposureOperationId_.clear();}
    const QString state=done.value("state").toString();if(state!="succeeded"){if(e)*e=state=="cancelled"?"Exposure cancelled":done.value("problem").toObject().value("message").toString("Exposure failed");return false;}
    auto result=done.value("result").toObject();f.id=result.value("frameId").toString();if(f.id.isEmpty()){if(e)*e="Exposure operation returned no frame id";return false;}
    auto preview=http_.get(nodeUrl("frames/"+f.id+"/preview"),30000);if(!accepted(preview,e))return false;auto d=preview.json.value("data").toObject();f.capturedUtc=QDateTime::fromString(d.value("capturedUtc").toString(),Qt::ISODateWithMs);f.exposureSec=r.exposureSec;f.gain=r.gain;f.binX=std::max(1,r.binX);f.binY=std::max(1,r.binY);f.source=id();QByteArray png=QByteArray::fromBase64(d.value("imagePngBase64").toString().toLatin1());std::vector<uchar> bytes(png.begin(),png.end());f.image=cv::imdecode(bytes,cv::IMREAD_UNCHANGED);if(f.image.empty()){if(e)*e="OAL preview did not contain a decodable image";return false;}size_={f.image.cols,f.image.rows};state_=ConnectionState::Connected;return true;
}
bool OalCameraClient::abortExposure(QString*e){QString id;{QMutexLocker lock(&exposureMutex_);id=activeExposureOperationId_;}if(id.isEmpty())return true;QUrl u(base_);QString path=u.path();const int marker=path.indexOf("/cameras/");if(marker>=0)path=path.left(marker);while(path.endsWith('/'))path.chop(1);u.setPath(path+"/operations/"+id+"/cancel");return accepted(http_.postJson(u,{},5000),e);}

QUrl OalMountClient::route(const QString&p)const{return appendPath(base_,p);}bool OalMountClient::accepted(const HttpJsonClient::Reply&r,QString*e)const{if(!r.ok()||!r.json.value("ok").toBool()){if(e)*e=r.error.isEmpty()?r.json.value("error").toObject().value("message").toString("OAL request failed"):r.error;return false;}return true;}
bool OalMountClient::connectDevice(QString*e){MountStatus s;if(!status(s,e)){state_=ConnectionState::Error;return false;}state_=ConnectionState::Connected;return true;}
bool OalMountClient::status(MountStatus&s,QString*e){auto r=http_.get(route("status"));if(!accepted(r,e))return false;auto d=r.json.value("data").toObject();s.connection=ConnectionState::Connected;s.coordinate={d.value("raDeg").toDouble(),d.value("decDeg").toDouble()};s.coordinateValid=d.contains("coordinateValid")?d.value("coordinateValid").toBool():true;s.tracking=d.value("tracking").toBool();s.slewing=d.value("slewing").toBool();s.parked=d.value("parked").toBool();return true;}
bool OalMountClient::slewTo(const EquatorialCoord&t,QString*e){return accepted(http_.postJson(route("slew"),coordToJson(t)),e);}bool OalMountClient::abortMotion(QString*e){return accepted(http_.postJson(route("abort"),{}),e);}bool OalMountClient::syncTo(const EquatorialCoord&t,QString*e){return accepted(http_.postJson(route("sync"),coordToJson(t)),e);}bool OalMountClient::setTracking(bool v,QString*e){return accepted(http_.postJson(route("tracking"),{{"enabled",v}}),e);}bool OalMountClient::park(bool v,QString*e){return accepted(http_.postJson(route("park"),{{"parked",v}}),e);}bool OalMountClient::pulseGuide(GuideDirection d,int ms,QString*e){QString n=d==GuideDirection::North?"north":d==GuideDirection::South?"south":d==GuideDirection::East?"east":"west";return accepted(http_.postJson(route("pulse-guide"),{{"direction",n},{"durationMs",ms}}),e);}
QUrl OalFocuserClient::route(const QString&p)const{return appendPath(base_,p);}bool OalFocuserClient::accepted(const HttpJsonClient::Reply&r,QString*e)const{if(!r.ok()||!r.json.value("ok").toBool()){if(e)*e=r.error.isEmpty()?r.json.value("error").toObject().value("message").toString("OAL request failed"):r.error;return false;}return true;}
bool OalFocuserClient::connectDevice(QString*e){FocuserStatus s;if(!status(s,e)){state_=ConnectionState::Error;return false;}state_=ConnectionState::Connected;return true;}bool OalFocuserClient::status(FocuserStatus&s,QString*e){auto r=http_.get(route("status"));if(!accepted(r,e))return false;auto d=r.json.value("data").toObject();s.connection=ConnectionState::Connected;s.position=d.value("position").toInt();s.moving=d.value("moving").toBool();return true;}bool OalFocuserClient::moveAbsolute(int p,QString*e){return accepted(http_.postJson(route("move"),{{"position",p}}),e);}bool OalFocuserClient::moveRelative(int d,QString*e){return accepted(http_.postJson(route("move-relative"),{{"delta",d}}),e);}bool OalFocuserClient::halt(QString*e){return accepted(http_.postJson(route("halt"),{}),e);}
}
