#ifdef OAS_HAVE_QHY
#include "backends/qhy_camera.h"
#include <QDateTime>

namespace oas {
static bool qok(uint32_t r,QString *e,const char *what){if(r==QHYCCD_SUCCESS)return true;if(e)*e=QString("%1 failed: %2").arg(what).arg(r);return false;}
bool QhyCamera::connectDevice(QString*e){if(!qok(InitQHYCCDResource(),e,"InitQHYCCDResource"))return false;resourceInitialized_=true;int count=ScanQHYCCD();if(count<=index_){if(e)*e=QString("QHY camera index %1 not found; count=%2").arg(index_).arg(count);disconnectDevice();return false;}char id[64]{};if(!qok(GetQHYCCDId(index_,id),e,"GetQHYCCDId")){disconnectDevice();return false;}cameraId_=QString::fromLatin1(id);handle_=OpenQHYCCD(id);if(!handle_){if(e)*e="OpenQHYCCD returned null";disconnectDevice();return false;}if(!qok(SetQHYCCDStreamMode(handle_,0),e,"SetQHYCCDStreamMode")||!qok(InitQHYCCD(handle_),e,"InitQHYCCD")){disconnectDevice();return false;}double chipW=0,chipH=0,pixW=0,pixH=0;uint32_t w=0,h=0,bpp=0;if(!qok(GetQHYCCDChipInfo(handle_,&chipW,&chipH,&w,&h,&pixW,&pixH,&bpp),e,"GetQHYCCDChipInfo")){disconnectDevice();return false;}sensorSize_={int(w),int(h)};SetQHYCCDResolution(handle_,0,0,w,h);state_=ConnectionState::Connected;return true;}
void QhyCamera::disconnectDevice(){if(handle_){CancelQHYCCDExposingAndReadout(handle_);CloseQHYCCD(handle_);handle_=nullptr;}if(resourceInitialized_){ReleaseQHYCCDResource();resourceInitialized_=false;}state_=ConnectionState::Disconnected;}
bool QhyCamera::capture(const ExposureRequest&r,CameraFrame&f,QString*e){if(!handle_){if(e)*e="QHY camera disconnected";return false;}SetQHYCCDParam(handle_,CONTROL_EXPOSURE,r.exposureSec*1e6);SetQHYCCDParam(handle_,CONTROL_GAIN,r.gain);SetQHYCCDParam(handle_,CONTROL_OFFSET,r.offset);SetQHYCCDBinMode(handle_,r.binX,r.binY);if(!qok(ExpQHYCCDSingleFrame(handle_),e,"ExpQHYCCDSingleFrame"))return false;uint32_t length=GetQHYCCDMemLength(handle_);std::vector<unsigned char> data(length);uint32_t w=0,h=0,bpp=0,ch=0;if(!qok(GetQHYCCDSingleFrame(handle_,&w,&h,&bpp,&ch,data.data()),e,"GetQHYCCDSingleFrame"))return false;if(ch==1&&bpp<=8)f.image=cv::Mat(int(h),int(w),CV_8UC1,data.data()).clone();else if(ch==1&&bpp<=16)f.image=cv::Mat(int(h),int(w),CV_16UC1,data.data()).clone();else if(ch==3&&bpp<=8)f.image=cv::Mat(int(h),int(w),CV_8UC3,data.data()).clone();else{if(e)*e=QString("Unsupported QHY frame: bpp=%1 channels=%2").arg(bpp).arg(ch);return false;}f.id="qhy-"+QDateTime::currentDateTimeUtc().toString("yyyyMMddTHHmmsszzz");f.capturedUtc=QDateTime::currentDateTimeUtc();f.exposureSec=r.exposureSec;f.gain=r.gain;f.source=id();return true;}
}
#endif
