#include "backends/synscan_network_mount.h"
#include "../../drivers/skywatcher/synscan_protocol.h"
#include <QElapsedTimer>
#include <QThread>
#include <QUrl>
#include <algorithm>

namespace oas {
SynScanNetworkMount::SynScanNetworkMount(QString e):endpoint_(std::move(e)){if(endpoint_.trimmed().isEmpty())endpoint_="127.0.0.1:11882";}
bool SynScanNetworkMount::parseEndpoint(QString&host,quint16&port,QString*error)const{QString text=endpoint_.trimmed();QUrl u=text.contains("://")?QUrl(text):QUrl("tcp://"+text);if(!u.isValid()||u.host().isEmpty()){if(error)*error="SynScan network endpoint must be host:port (default SynScan Communication Protocol TCP port is 11882)";return false;}host=u.host();port=u.port(11882);return true;}
bool SynScanNetworkMount::exchange(const QByteArray&cmd,QByteArray&reply,int timeoutMs,QString*error){if(socket_.state()!=QAbstractSocket::ConnectedState){if(error)*error="SynScan TCP socket is not connected";return false;}while(socket_.bytesAvailable())socket_.readAll();if(socket_.write(cmd)!=cmd.size()||!socket_.waitForBytesWritten(std::min(timeoutMs,1500))){if(error)*error="SynScan TCP write failed: "+socket_.errorString();return false;}QElapsedTimer t;t.start();reply.clear();while(t.elapsed()<timeoutMs){if(!socket_.waitForReadyRead(std::min(100,std::max(1,timeoutMs-int(t.elapsed())))))continue;reply+=socket_.readAll();while(socket_.waitForReadyRead(5))reply+=socket_.readAll();if(reply.contains('#'))return true;}if(error)*error=QString("SynScan TCP reply timeout; received '%1'").arg(QString::fromLatin1(reply.toHex(' ')));return false;}
bool SynScanNetworkMount::connectDevice(QString*error){state_=ConnectionState::Connecting;QString host;quint16 port;if(!parseEndpoint(host,port,error)){state_=ConnectionState::Error;return false;}socket_.connectToHost(host,port);if(!socket_.waitForConnected(5000)){if(error)*error="Could not connect to SynScan Communication Protocol TCP server "+host+":"+QString::number(port)+": "+socket_.errorString();state_=ConnectionState::Error;return false;}QByteArray r;if(!exchange(QByteArray::fromStdString(oal::synscan::echoProbe('O')),r,3000,error)||r!=QByteArrayLiteral("O#")){if(error&&error->isEmpty())*error="SynScan TCP echo handshake failed";socket_.disconnectFromHost();state_=ConnectionState::Error;return false;}r.clear();if(exchange(QByteArrayLiteral("m"),r,2000,nullptr)&&r.size()>=2)model_=int(static_cast<unsigned char>(r[0]));state_=ConnectionState::Connected;return true;}
void SynScanNetworkMount::disconnectDevice(){if(socket_.state()!=QAbstractSocket::UnconnectedState){socket_.disconnectFromHost();socket_.waitForDisconnected(1000);}state_=ConnectionState::Disconnected;}
bool SynScanNetworkMount::status(MountStatus&s,QString*error){QByteArray r;if(!exchange("e",r,3000,error))return false;double ra=0,dec=0;if(!oal::synscan::parsePreciseRaDec(r.trimmed().toStdString(),ra,dec)){if(error)*error="Invalid SynScan network RA/DEC reply";return false;}s.connection=state_;s.coordinate={ra,dec};QByteArray tr;if(exchange("t",tr,1500,nullptr)&&!tr.isEmpty())s.tracking=static_cast<unsigned char>(tr[0])!=0;QByteArray busy;if(exchange("L",busy,1500,nullptr)&&!busy.isEmpty())s.slewing=busy.startsWith('1');s.parked=false;s.pierSide="unknown";QByteArray side;if(exchange("p",side,1200,nullptr)){if(side.startsWith('E'))s.pierSide="east";else if(side.startsWith('W'))s.pierSide="west";}return true;}
bool SynScanNetworkMount::slewTo(const EquatorialCoord&t,QString*error){QByteArray r;if(!exchange(QByteArray::fromStdString(oal::synscan::gotoRaDec(t.raDeg,t.decDeg)),r,3000,error))return false;if(!r.endsWith('#')){if(error)*error="SynScan network GOTO rejected";return false;}return true;}
bool SynScanNetworkMount::abortMotion(QString*error){QByteArray r;const bool a=exchange("M",r,2000,error)&&r.endsWith('#');QString dummy;fixedRate(true,true,0,&dummy);fixedRate(false,true,0,&dummy);return a;}
bool SynScanNetworkMount::syncTo(const EquatorialCoord&t,QString*error){QByteArray r;return exchange(QByteArray::fromStdString(oal::synscan::syncRaDec(t.raDeg,t.decDeg)),r,3000,error)&&r.endsWith('#');}
bool SynScanNetworkMount::setTracking(bool enabled,QString*error){QByteArray c;c.append('T');c.append(char(enabled?(model_>=0&&model_<128?2:1):0));QByteArray r;return exchange(c,r,2000,error)&&r.endsWith('#');}
bool SynScanNetworkMount::park(bool,QString*error){if(error)*error="SynScan Communication Protocol 3.3 does not define a normative park command";return false;}
bool SynScanNetworkMount::fixedRate(bool raAxis,bool positive,int rate,QString*error){QByteArray c;c.append('P');c.append(char(2));c.append(char(raAxis?16:17));c.append(char(positive?36:37));c.append(char(std::clamp(rate,0,9)));c.append(char(0));c.append(char(0));c.append(char(0));QByteArray r;return exchange(c,r,2000,error)&&r.endsWith('#');}
bool SynScanNetworkMount::pulseGuide(GuideDirection dir,int ms,QString*error){const bool ra=dir==GuideDirection::East||dir==GuideDirection::West;const bool pos=dir==GuideDirection::East||dir==GuideDirection::North;if(!fixedRate(ra,pos,1,error))return false;QThread::msleep(unsigned(std::clamp(ms,1,5000)));return fixedRate(ra,pos,0,error);}
}
