#!/usr/bin/env python3
from pathlib import Path
import sys
root=Path(__file__).resolve().parents[1]
checks=[]
def has(path,needle,label):
    text=(root/path).read_text(encoding='utf-8',errors='replace')
    checks.append((needle in text,label))
def lacks(path,needle,label):
    text=(root/path).read_text(encoding='utf-8',errors='replace')
    checks.append((needle not in text,label))

has('CMakeLists.txt','VERSION 0.2.10.58','release version')
has('CMakeLists.txt','OAS_ENABLE_WEBRTC','WebRTC build option')
has('CMakeLists.txt','find_package(LibDataChannel CONFIG QUIET)','libdatachannel discovery')
has('CMakeLists.txt','OAS_HAVE_WEBRTC=1','compile feature guard')
has('CMakeLists.txt','LibDataChannel::LibDataChannel','shared imported target supported')
has('CMakeLists.txt','LibDataChannel::LibDataChannelStatic','static imported target supported')
has('CMakePresets.json','OAS_REQUIRE_WEBRTC','official Windows preset requires dependency')
has('scripts/bootstrap_native_dependencies.ps1','libdatachannel:x64-windows','Windows vcpkg bootstrap')
has('scripts/bootstrap_native_dependencies.sh','libdatachannel/$webrtc_version','Linux per-user bootstrap')
has('scripts/build_windows.ps1','LibDataChannel_DIR','Windows CMake package forwarding')
has('scripts/build_linux.sh','LibDataChannel_DIR','Linux CMake package forwarding')
has('src/oal/oal_ws_server.cpp','path=="/webrtc"','dedicated signaling WebSocket')
has('src/oal/oal_ws_server.cpp','rtcCreatePeerConnection','node creates WebRTC peer')
has('src/oal/oal_ws_server.cpp','rtcCreateDataChannelEx(peer->pc,"oalv-main"','main DataChannel')
has('src/oal/oal_ws_server.cpp','rtcCreateDataChannelEx(peer->pc,"oalv-guide"','guide DataChannel')
has('src/oal/oal_ws_server.cpp','init.reliability.unordered=true','unordered preview transport')
has('src/oal/oal_ws_server.cpp','init.reliability.unreliable=true','partially unreliable preview transport')
has('src/oal/oal_ws_server.cpp','init.reliability.maxPacketLifeTime=150','bounded retransmission lifetime')
has('src/oal/oal_ws_server.cpp','init.protocol="oalw-v1"','DataChannel protocol name')
has('src/oal/oal_ws_server.cpp','constexpr int kWebRtcFragmentPayload=48*1024','48 KiB application fragmentation')
has('src/oal/oal_ws_server.cpp','constexpr int kWebRtcBufferedLimit=2*1024*1024','backpressure limit')
has('src/oal/oal_ws_server.cpp','rtcGetBufferedAmount(dc)','buffered amount check')
has('src/oal/oal_ws_server.cpp','memcpy(d,"OALW",4)','OALW v1 fragment envelope')
has('src/oal/oal_ws_server.cpp','rtcSendMessage(dc,fragment.constData()','binary DataChannel send')
has('src/oal/oal_ws_server.cpp','qEnvironmentVariable("OAL_WEBRTC_ICE_SERVERS")','STUN/TURN configuration')
has('src/core/remote_observatory_controller.cpp','webrtcWsUrl_.setPath("/webrtc")','remote signaling endpoint')
has('src/core/remote_observatory_controller.cpp','rtcSetDataChannelCallback','remote incoming DataChannels')
has('src/core/remote_observatory_controller.cpp','label=="oalv-main"','remote main role routing')
has('src/core/remote_observatory_controller.cpp','label=="oalv-guide"','remote guide role routing')
has('src/core/remote_observatory_controller.cpp','m.left(4)!="OALW"','OALW decoder')
has('src/core/remote_observatory_controller.cpp','if(a.fragmentCount&&seq<a.sequence)return','latest-sequence discard semantics')
has('src/core/remote_observatory_controller.cpp','consumeVideoPacket(packet,"webrtc-datachannel")','reassembled OALV delivery')
has('src/core/remote_observatory_controller.cpp','const bool fullRtc=webrtcMainOpen_','fallback waits for both role channels')
has('src/core/remote_observatory_controller.cpp','if(rtcRole)return','per-role WebSocket duplicate suppression')
has('src/core/remote_observatory_controller.cpp','stats["networkTransport"]=networkTransport','transport telemetry')
has('src/gui/main_window.cpp','networkTransport','Dual Live transport telemetry display')
has('src/core/application_controller.cpp','{"webrtc",webrtc}','node capability advertisement')
has('src/core/application_controller.cpp','"OALV v1/JPEG in OALW v1 DataChannel fragments"','payload capability is explicit')
has('src/core/application_controller.cpp','appendSer(frame,serError)','SER remains in acquisition path')
has('src/core/application_controller.cpp','previewBusy->exchange(true)','preview remains droppable')
has('src/oal/oal_ws_server.cpp','QThreadPool::globalInstance()->start','JPEG/network processing stays downstream')
has('src/oal/oal_ws_server.cpp','path=="/video"','OALV WebSocket fallback retained')
lacks('src/oal/oal_ws_server.cpp','rtcAddTrack','no claim of RTP media-track codec in v1')

failed=[label for ok,label in checks if not ok]
for ok,label in checks: print(('PASS' if ok else 'FAIL')+': '+label)
print(f'WebRTC preview transport: {len(checks)-len(failed)}/{len(checks)} checks passed')
if failed: sys.exit(1)
